<?php 
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_install().
 */
function onesip_role_promote_install() {
    //Create new roles
    $my_roles =[];
    $my_roles[0]['id'] = 'rejected_additional_access_';
    $my_roles[0]['label'] = 'Rejected Additional Access';
    
    for ($i = 0; $i < count($my_roles); $i++) {
      //your data array
      $data = array('id' => $my_roles[$i]['id'], 'label' => $my_roles[$i]['label']);
      //creating your role
      $role = \Drupal\user\Entity\Role::create($data);
      //saving your role
      $role->save();
      drupal_set_message('Added role: Rejected Additional Access.');
      drupal_set_message('Please enable the Webform Handler: onesip_role_promote_additional_access_request_handler');
    }
}


/**
 * Implements hook_install().
 */
function onesip_role_promote_uninstall() {
    //Create new roles
    $my_roles =[];
    $my_roles[0]['id'] = 'rejected_additional_access_';
    $my_roles[0]['label'] = 'Rejected Additional Access';
    
    for ($i = 0; $i < count($my_roles); $i++) {
      //your data array
      $data = array('id' => $my_roles[$i]['id'], 'label' => $my_roles[$i]['label']);
      //creating your role
      $role = \Drupal\user\Entity\Role::create($data);
      //saving your role
      $role->delete();
      drupal_set_message('Deleted role: Rejected Additional Access.');
    }
}

function onesip_role_promote_form_alter(&$form, &$form_state, $form_id) {
  $is_views_bulk_operations_configure_action = strpos($form_id, 'views_bulk_operations_configure_action')!==FALSE;
  if ($is_views_bulk_operations_configure_action) {
    // Fix empty string default value, causing "An illegal choice has been detected".  
    $form['rid']['#default_value'] = NULL; // Validates RID as a required field
  }
}
/**
 * Implements hook_webform_element_alter().
 *
 * @param array              $element
 * @param FormStateInterface $form_state
 * @param array              $context
 */
function onesip_role_promote_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
    //  check for desired element
    //  webform_submission_create_promoted_role_request_add_form
    //  webform-submission-create-promoted-role-request-add-form--edit-requested-role-business-owner
    //  strpos(haystack, needle)
    //  create_promoted_role_request--requested_role

    // Add webform element validation.
    if (isset($element['#webform_id']) && strpos($element['#webform_id'], 'role') !== FALSE) {
        $element['#element_validate'][] = array(
            'Drupal\onesip_role_promote\Validate\RolePromoteValidateConstraint',
            'validate'
        );
    }
}